### ISSUE TITLE
Import fails in Godot 3.2 beta 2

### ISSUE THREAD

**Issue by Wavesonics** [ShiftyAxel/Qodot#20]
I added the plugin to the 3.2 beta to see if any updates will be required for, and it appears to fail currently:
```
ERROR: Cannot get class 'QuakeMap'.
   At: core/class_db.cpp:343
```

**Comment by ShiftyAxel** [comment]
Curious, do any obvious errors appear in the log if you open addons/qodot/resources/quake_map.gd in the editor?

I've not messed with 3.2 at all yet, but support will be inevitable given time!

**Comment by ShiftyAxel** [comment]
This is fixed- turns out it was an issue with class names getting changed in the code, but not in serialized import files.

The latest commit to master fixes the import plugin, but you'll need to reimport all of your maps (and possibly their entries in the .import folder, along with the inline .import files generated by the editor) in order for the error to go away.
